name: Deploy main to EC2
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    
jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            DB_HOST: ${{ secrets.RDS_HOSTNAME }}
            DB_PASSWORD: ${{ secrets.RDS_USERNAME}}
            DB_PORT: ${{ secrets.RDS_PORT }}
            DB_NAME: bookstore
            SERVER_PORT: 6000
        steps: 
            - name: Checkout 
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Login to dockerHub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_HUB_TOKEN}}
                password: ${{secrets.DOCKER_HUB_TOKEN}}
            - name: prepare the docker-compose run  
              run: |
                    ls -l

            - name: Build and push
              uses: docker/build-push-action@v4
              with: 
                context: .
                push: true
                tags: 29ayenyeinsan/webstore_frontend
            - name: copy file via ssh password
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{secrets.HOST_SERVER}}
                username: ${{secrets.HOST_USER_NAME}}
                key: ${{ secrets.HOST_SSH_PRIVATE_KEY}}
                port: 22
                source: |
                   docker-compose-main.yml
                target: "/home/ubuntu/webstore_frontend"
            - name: docker compose
              uses: appleboy/ssh-action@v0.1.10
              with: 
                host: ${{secrets.HOST_SERVER}}
                username: ${{secrets.HOST_USER_NAME}}
                key: ${{secrets.HOST_SSH_PRIVATE_KEY}}
                port: 22
                script: |
                    sudo apt-get update
                    sudo apt-get install -y docker
                    sudo apt-get install -y docker-compose
                    sudo usermod -aG docker ubuntu
                
                     cd /home/ubuntu/webstore_frontend
                     echo ${{secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
                     sudo docker-compose down
                     sudo docker-compose pull
                    
                     sudo docker-compose -f /home/ubuntu/webstore_frontend/docker-compose-main.yml up -d

                     sudo docker exec  webstoreFrontend_main_1 sh -c 'echo "RDS_HOSTNAME=${{secrets.RDS_HOSTNAME }}" >> /frontend/.env'
                     sudo docker exec   webstoreFrontend_main_1 sh -c 'echo " RDS_USERNAME=${{ secrets.RDS_USERNAME}}" >> /frontend/.env'
                     sudo docker exec  webstoreFrontend_main_1  sh -c 'echo " RDS_PASSWORD=${{secrets.RDS_PASSWORD}}" >> /frontend/.env'
                     sudo docker exec  webstoreFrontend_main_1 sh -c 'echo "RDS_PORT=${{secrets.RDS_PORT}}" >> /frontend/.env'
                     sudo docker restart  webstoreFrontend_main_1


                    





       